import { Outfit, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight : ["300", "400", "500", "600", "700", "800", "900"]
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight : ["300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body
        className={`${outfit.variable} ${raleway.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
